  
version: 0.2

phases:
  # install:
  #   commands:
  #     - npm install
  build:
    commands:
      - echo "This is CI/CD Sample Project"
      - ls -lart $CODEBUILD_SRC_DIR/dags/*
      - aws s3 sync $CODEBUILD_SRC_DIR/dags/ $dev_s3_bucket_dags --delete
